### PR TITLE
Container With Most Water

### PR DESCRIPTION
**Pull request by vibhoooo**
I have added a java program along with reaadme file.Please review my Pr and merge it

### CODE REVIEW

**Review by DurveshKumarPal — COMMENTED** [review]
@vibhoooo You need to add a Problem link in the problem title

**Comment by DurveshKumarPal** [comment]
You have to add in Problem Name or Title

**Comment by vibhoooo** [comment]
fine?

**Review by DurveshKumarPal — APPROVED** [review]

**Comment by vibhoooo** [comment]
Done

**Pull request merged**
